[local]
locall ansible_host=192.168.1.20 ansible_user=ayush ansible_ssh_pass=Ayush9496@  

[azure]
azure_vm ansible_host=172.171.236.12 ansible_user=ayush ansible_ssh_pass=marvel754396@ 

[demo:children]
local
azure

[demo:vars]

 